export const CREATE_CONTACT_REQUEST = 'CREATE_CONTACT_REQUEST';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAILURE = 'CREATE_CONTACT_FAILURE';

export const GET_ALL_CONTACTS_REQUEST = 'GET_ALL_CONTACTS_REQUEST';
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_FAILURE = 'GET_ALL_CONTACTS_FAILURE';

export const SEARCH_ALL_CONTACTS_SUCCESS = 'SEARCH_ALL_CONTACTS_SUCCESS';
